/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f2f0f0',
        'surface-container-high': '#e9e8e7',
        'tertiary-fixed': '#e0e0ff',
        'on-surface-variant': '#46464e',
        'primary': '#04072E',
        'on-secondary': '#ffffff',
        'surface-variant': '#e4e2e2',
        'on-tertiary-fixed-variant': '#363e91',
        'surface-container-low': '#f5f3f3',
        'surface': '#fbf9f9',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#c0c3f3',
        'surface-container': '#efeded',
        'secondary': '#bb000f',
        'on-tertiary-fixed': '#010766',
        'tertiary-fixed-dim': '#bec2ff',
        'surface-container-highest': '#e4e2e2',
        'secondary-container': '#e51c1f',
        'on-primary-fixed': '#14183d',
        'primary-fixed': '#dfe0ff',
        'tertiary': '#000000',
        'outline': '#77767f',
        'on-surface': '#1b1c1c',
        'on-secondary-fixed': '#410002',
        'primary-container': '#14183d',
        'inverse-surface': '#303031',
        'secondary-fixed': '#ffdad5',
        'on-secondary-container': '#fffbff',
        'on-primary-fixed-variant': '#40446b',
        'on-background': '#1b1c1c',
        'outline-variant': '#c7c5cf',
        'error-container': '#ffdad6',
        'surface-bright': '#fbf9f9',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#ffb4ab',
        'on-secondary-fixed-variant': '#930009',
        'surface-dim': '#dbdad9',
        'on-tertiary-container': '#747cd3',
        'inverse-primary': '#c0c3f3',
        'on-error-container': '#93000a',
        'on-primary-container': '#7d81ac',
        'surface-tint': '#575b85',
        'tertiary-container': '#010766',
        'background': '#fbf9f9',
        'error': '#ba1a1a',
      },
      fontFamily: {
        'headline': ['Newsreader', 'serif'],
        'body': ['Public Sans', 'sans-serif'],
        'label': ['Public Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      boxShadow: {
        editorial: '0 30px 60px -12px rgba(27, 28, 28, 0.08)',
      },
    },
  },
  plugins: [],
}
